### ISSUE TITLE
Package causes atom to scroll up when right clicking

### ISSUE THREAD

**Issue by seanthomas0409** [bmoren/p5js-snippets#16]
When right clicking on text, the atom editor scrolls up

**Comment by bmoren** [comment]
are you sure this is the snippets and not the p5.toolbar or some other package, did you try turning all other packages off? I just want to make sure that I focus my efforts in the right place. @tstefanich I'm fairly sure that this has to do with the right click to find in the reference in this package that you implemented, any chance you can take a look?

**Comment by bmoren** [comment]
I didnt see this before, but it looks like there is actually a pull request for this bug already, I'll have a look at it this afternoon!

**Comment by seanthomas0409** [comment]
> are you sure this is the snippets and not the p5.toolbar or some other package, did you try turning all other packages off? I just want to make sure that I focus my efforts in the right place. @tstefanich I'm fairly sure that this has to do with the right click to find in the reference in this package that you implemented, any chance you can take a look?

So I tested it in safe mode and the bug disappeared. So I disabled all my plugins and tried to recreate the bug. I discovered that the bug only reappears when p5js-snippets is enabled. I have also just tried without p5js-toolbar (only snippets) and the bug does indeed reappear. (I have not tried disabling all my plugins except snippets though)
Thank you for your effort.

**Comment by bmoren** [comment]
thanks for the report. this is clearly an issue with the snippets and there was a pull request, so I should have a fix / new version going out momentarily (with an update to the most recent version of p5 also!)

**Comment by bmoren** [comment]
This should be sorted out with the new 0.4.3 release I just sent out, let me know if you run into any issues! thanks for the report!
